osx_image: xcode7.3

dist: trusty
sudo: false

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache

env:
  global:
    - secure: "m4HJnP/OHWzxl2xrgzBU6pAqwR77M1gPNDeJ4QunIi3MRhFehLPQ5JMW8thTnO8zAeWhdr5zXs0WxgGjcifALtWT9ushezjp3AAT/fk0Btoia5fXrqMDs2x7NDMci8026IYRK2SzpR29OggPfdMHk+hODEOuldPmgEI8tQMp1ytJlwsGyGwH+PwZNrQTZ85bhKUGsgFHIMH9RzvzmlKJP2WCuIV5nhCu+OQt1V4qhYdrCmwBpoW6JCY3Pi+QTLZK3dJVBJfKl9eC3RBnes52vl9xyCNMLC+ui+YYpq59wBOhkNcb24+JJIbf8LQ4Lv20lDS/jpp6w8MS5n6/vj5rDpRoBsRIEIO5jvNi0nmYDDoEFqNFkwszAcWzEh3GtSifdijum4dA73m9RfX0q0i46+jucsRAnozEFo5/fzxl0Y2yJjbr9fLuNPfIQQWtG3fQKZG9vnBUN9jt95JOBYoi49IfgsWsXXT//lrzS/qdzcIjWeAjNII5q2QVdXgFpow4hX+3yTyh+f0X2MX3ywpyc0QXG5cm+AF86hc2x8Pc0lld9l96iQSxaZPcQcIv68XYks9xGSU94aPO5um/WFnaXabHM0lQPZLXpLKOfZ8IJgFb0m1CkDEuH4cYURGg/QhMsk1FRAWy88Z6JRRFUfNf7HXaJdDiQXdFIdFf0eYBsLE="

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
  - nvm install 7
  - npm install

script:
  - node --version
  - npm --version
  - echo Packing
  - npm run pack
  - echo Publishing
  - GH_REPO="@github.com/Onset/git-latex.git"
  - FULL_REPO="https://$GH_TOKEN$GH_REPO"
  - cd dist
  - git init
  - git config user.email "chalupa.filip@gmail.com"
  - git config user.name "Filip Chalupa"
  - git add .
  - git commit -m "Deploy"
  - git push --force --quiet $FULL_REPO master:package/$TRAVIS_OS_NAME

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
