version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - npm install

environment:
  GH_TOKEN:
    secure: Ay7kOpI0QRhbqqH+FgJsvDGSB1o9e+YNMYreVdYLXhd4fo6pZ4D5F5Y/2a/GjHm9

build_script:
  - node --version
  - npm --version
  - echo Packing
  - npm run pack
  - echo Publishing
  - SET GH_REPO=@github.com/Onset/git-latex.git
  - SET FULL_REPO=https://%GH_TOKEN%%GH_REPO%
  - cd dist
  - git init
  - git config user.email "chalupa.filip@gmail.com"
  - git config user.name "Filip Chalupa"
  - git add .
  - git commit -m "Deploy"
  - git push --force --quiet %FULL_REPO% master:package/windows


test: off
