os: unstable

environment:
  matrix:
    - nodejs_version: 7

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - npm run prebuild
  - npm run build

artifacts:
  - path: 'dist'
    name: release-archive
    type: zip

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: /7T74glgVe7tT6igUGJXrvGhyyOkCz1IZExWehPM5QqzSC2E3PfrGTN7n87+ebWk
  artifact: release-archive
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
