version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@8.6.0
  - npm install
  - npm prune

environment:
  GH_TOKEN:
    secure: Ay7kOpI0QRhbqqH+FgJsvDGSB1o9e+YNMYreVdYLXhd4fo6pZ4D5F5Y/2a/GjHm9

build_script:
  - node --version
  - npm --version
  - npm run pack
  - .\.publish_to_github.bat

test: off